### PR TITLE
Retry 3 times reading repo participation from the Github API

### LINKED ISSUE #40: Twig Extension undefined index notice
The ReactPHP website displays a PHP notice with its [stack trace](https://pastebin.com/XcGJwG3A) in the `activity` box on the lower right (see attached screenshot).

This happens because the `$participation` array does not contain the index `all`. Might have sth. to do with connectivity issues to Travis, or maybe they changed something on their side? 

auswahl_029

### PR DESCRIPTION
**Pull request by jsor**
Looks like that [endpoint](https://api.github.com/repos/reactphp/event-loop/stats/participation) is quite unreliable and sometimes returns just an empty result.

After 3 retries, an exception is thrown.

Closes #40

### CODE REVIEW

**Comment by jsor** [comment]
Bonus: [`goto`](https://github.com/igorw/retry/blob/master/src/retry.php#L17)!

File: src/data.php [hunk 1]
```diff
@@ -12,7 +13,18 @@ function components(Client $client, CacheItemPoolInterface $markdownCache): arra
...
-        $component['participation'] = $client->repo()->participation($username, $repository);
+
+        $component['participation'] = retry(3, function () use ($client, $username, $repository){
+            $participation = $client->repo()->participation($username, $repository);
+
+            if (!isset($participation['all'])) {
+                throw new \RuntimeException(
+                    "Could not fetch participation for $username/$repository from the Github API"
+                );
+            }
```
Comment (clue) [inline src/data.php]: It's my understanding that the real fix here is properly fail the build if this API fails? I've tried to reproduce this locally, but could not manage to make it fail, so I suppose this is something we may want to report upstream?

An additional "retry" functionality may or may not be needed, depending what the cause for this error is. That being said, I see no harm in this and as such: LGTM :+1:
